apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vote-app-uat
  name: vote-api-uat-configmap
  namespace: default
data:
  application.yml: |- 
    server:
      port: 8081
      servlet:
        context-path: /VoteService

    spring:
      redis:
        redisson: 
          file: file:///app/config/redisson.yml

    vote:
      question: "這季NBA冠軍賽，你支持哪一隊呢？"
      options:
        - optionId: "01"
          label: "金塊"
          bgColor: "#FFD700"
        - optionId: "02"
          label: "熱火"
          bgColor: "#FF4500"
        - optionId: "03"
          label: "湖人"
          bgColor: "#552583"
        - optionId: "04"
          label: "勇士"
          bgColor: "#006BB6"

  redisson.yml: |- 
    singleServerConfig:
      address: "redis://vote-api-uat-redis:6379"
      database: 0
      connectionMinimumIdleSize: 5
      connectionPoolSize: 200
      connectTimeout: 10000
      timeout: 20000
      password: uat-redis
    threads: 8
    nettyThreads: 32

  logback-spring.xml: |- 
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <springProperty scope="context" name="serverName" source="HOSTNAME" />
      <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{sessionId}][%X{clientIp}][%X{token}][%X{companyUid}] %logger{10} line:%L - %msg%n</pattern>
          <charset>utf8</charset>
        </encoder>
      </appender>
      <root level="info">
        <appender-ref ref="console" />
      </root>
    </configuration>
