apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-app-dev
  name: vote-api-dev
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: vote-api-dev-svc
  sessionAffinity: None
  type: ClusterIP
