apiversion: v1
kind: Pod
metadata:
  labels:
    app: vote-api-dev-redis
  name: redis
  namespace: default
spec:
  containers:
  - image: redis:7.2-rc2-alpine
    imagePullPolicy: Always
    name: redis
    args:
    - -c
    - redis-server /usr/local/etc/redis/redis.conf --requirepass dev-redis
    command:
    - /bin/sh
    resources:
      requests:
        cpu: "200m"
        memory: "600Mi"
      limits:
        cpu: "200m"
        memory: "600Mi"
    volumeMounts:
    - mountPath: /usr/local/etc/redis/redis.conf
      name: app-config
      readOnly: true
      subPath: redis.conf
  restartPolicy: Always
  volumes:
  - name: app-config
    configMap:
      defaultMode: 420
      name: vote-api-dev-redis-configmap