name: CI for Dev

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'deploy/**'

env:
  IMAGE_NAME: yjring/demo_app
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  ACCESS_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Extract version
      id: extract_version
      run: echo "::set-output name=VERSION::dev-$(echo ${GITHUB_SHA::6})"
    
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: main
        token: ${{ env.ACCESS_TOKEN }}
      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven and generate reports
      run: mvn -B package --file backend/pom.xml

    - name: Test with Maven
      run: mvn test --file backend/pom.xml
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }}

    - name: Update Kubernetes deployment
      run: |
        find ./deploy -type f -name "*.yaml" -exec sed -i 's@image: .*@image: '"${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }}"'@' {} \;

    - name: Commit changes
      run: |
        git config --local user.email "bot"
        git config --local user.name "bot"
        git add ./deploy/*.yaml
        git commit -m "Update image version to ${{ steps.extract_version.outputs.VERSION }}" -a
        git push origin main
