name: Update API ConfigMap

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/src/main/resources/*'

env:
  ACCESS_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.head_ref }}
          token: ${{ env.ACCESS_TOKEN }}

      - name: Update redisson.yml
        run: |
          sed -i 's|redis://127.0.0.1:6379|redis://vote-api-dev-redis:6379|' backend/src/main/resources/redisson.yml
          sed -i 's|file: classpath:redisson.yml|file: file:///app/config/redisson.yml|' backend/src/main/resources/application.yml

      - name: Update API ConfigMap
        run: |
          kubectl create configmap vote-api-dev-configmap -n default --from-file=backend/src/main/resources/ --dry-run=client -o yaml > deploy/dev/api-configMap.yaml
          cat deploy/dev/api-configMap.yaml

      - name: Commit and push
        run: |
          git config --local user.email "PipelineBot"
          git config --local user.name "PipelineBot"
          git add ./deploy/dev/api-configMap.yaml
          git commit -m "Update api-configMap.yaml due to changes in /backend/src/resources"
          git push origin ${{ github.head_ref }}
